### ISSUE TITLE
Shrink to only show favicons

### ISSUE THREAD

**Issue by krruzic** [eoger/tabcenter-redux#139]
Not sure how feasible this is, but this is a must-have feature for me. Hopefully it's possible

**Comment by eoger** [comment]
Have you checked the compact mode in the settings page?

**Comment by lopis** [comment]
@krruzic I use some custom `userChrome.css` to allow the sidebar to be very narrow, and also to hide some of the controls from the sidebar.

![image](https://user-images.githubusercontent.com/2715751/29161035-f544641e-7db4-11e7-8130-20d0f70082d6.png)


```css
    #tabbrowser-tabs {
      visibility: collapse !important;
    }

    #sidebar-box {
      overflow-x: hidden;
      min-width: 0 !important;
    }

    #sidebar-header {
      position: relative;
      z-index: 1;
    }
    /* Hides tab center header (search bar) */
    #sidebar {
      margin-top: -37px;
      position: relative;
      z-index: 0;
    }

    #newtab-label, #newtab  {
      display: none !important;
    }

    #settings {
      display: none !important;
    }

    /* Hides sidebar switcher text */
    #sidebar-switcher-target label {
      display: none;
    }

    /* Hides sidebar close button */
    #sidebar-close {
      display: none;
    }
```
