### ISSUE TITLE
Hide the default tab strip

### ISSUE THREAD

**Issue by eoger** [eoger/tabcenter-redux#15]
Probably the biggest and most important blocker. Bug at https://bugzilla.mozilla.org/show_bug.cgi?id=1332447

**Comment by Smile4ever** [comment]
Talked about in yesterdays triage meeting (2017-06-21) for WebExtensions. 

Agenda and outcome from the triage meeting (page 2, first item):
https://docs.google.com/document/d/1s2j85VfYKTDftppFU-K7pgRs6sEuMTHVXqf3RL5iYvs/edit#heading=h.t2yykqfh2jii

**Comment by mlissner** [comment]
Are there any workarounds for this? I'd be more inclined to test if I could hide the top tabs.

**Comment by Keith94** [comment]
@mlissner You can try my workaround. Just add the following to [userChrome.css](http://kb.mozillazine.org/index.php?title=UserChrome.css).

```css
#TabsToolbar {
	visibility: collapse !important;
}
```

Enabling the title bar is also recommended.

**Comment by lopis** [comment]
@Keith94 This fix should be ni the readme, really.

**Comment by april** [comment]
Note that @Keith94's recommendation above causes glitches with the open/close/minimize buttons being overlaid on top of the navigation buttons, at least on macOS. This accomplishes the same thing but without those glitches:

```css
@-moz-document url("chrome://browser/content/browser.xul") {
  #TabsToolbar {
    height: 22px;
  }

  #tabbrowser-tabs {
    visibility: collapse;
  }
}
```

I also add `#sidebar-header` to `visibility: collapse`, which saves a ton of vertical space in the sidebar. It really should scroll, but that's probably for another bug entirely.

**Comment by mlissner** [comment]
I wonder, is there a way to do the CSS so that if the sidebar is open, the tab strip is hidden, and if not, the tab strip is shown? There's a new button in the customize menu that opens/closes the sidebar. If the CSS did what I'm describing, the new button could serve to switch between tabs on top and sidebar, just by showing/hiding the sidebar.

**Comment by eoger** [comment]
Currently trying to come up with a patch for bug 1332447, here's what I came up with:

```css
#TabsToolbar {
  min-height: 31.5px (Windows) / 27px (macOs) / no rule on linux
}

#TabsToolbar > * {
   visibility: collapse;
}
```

**Comment by rcchen** [comment]
I finally found a solution I'm pretty happy about in FF57 for OS X, though it requires two changes:

The first is the CSS fix as described above. Here's the contents of my `userChrome.css` file
```css
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");
@-moz-document url("chrome://browser/content/browser.xul") {
  #TabsToolbar {
    visibility: collapse;
  }
}
```

The second part is right clicking on the URL bar, going to customize, and enabling the title bar. This gives the Mac OS buttons a place to go:

<img width="435" alt="image" src="https://user-images.githubusercontent.com/1175041/31243686-8c6c7b44-a9be-11e7-9d64-8b740d125bed.png">

Checkbox is at the bottom:

<img width="369" alt="image" src="https://user-images.githubusercontent.com/1175041/31244247-aaf02c82-a9be-11e7-988c-6f0c0b8a742b.png">

Hope that helps out someone as we wait for the hide tab API to merge!

**Comment by jhasse** [comment]
This should have the D-tabcenter-parity label, right?

**Comment by brandonchartier** [comment]
According to the [mozillazine kb](http://kb.mozillazine.org/UserChrome.css_Element_Names/IDs), `tab` might be a more appropriate selector. I've found this to behave better on Windows than previous suggestions, but I haven't been able to test on a Mac yet.

```css
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");
@-moz-document url("chrome://browser/content/browser.xul") {
  tab {
    visibility: collapse;
  }
}
```

**Comment by RalfJung** [comment]
I followed the wiki recommendations for hiding the tab strip:
```
#tabbrowser-tabs {
  visibility: collapse;
}
```

However, there are at least two issues with with:
* In private windows, there is a weird empty bar with a mask in it at the top of the window:
![private](https://user-images.githubusercontent.com/330628/32148147-ce7d9f08-bcf2-11e7-9a22-bcfcbe17b470.png)
* In full-screen mode, the window controls (minimize, ...) appear at the top *left* of the window rather than the top right.

**Comment by ugggf** [comment]
Hi, I tried all the above userChrome.css ways (Firefox 57.0b12 64-bit in Linux Mint) but couldn't affect the presence of the horizontal tabbar. Anyone tried in linux and succeeded?

**Comment by ffledgling** [comment]
@ugggf See brandonchartier's commet above ( https://github.com/eoger/tabcenter-redux/issues/15#issuecomment-336190386 ), which works for me on Ubuntu 16.04, with firefox nightly.

**Comment by dos1** [comment]
Also, see https://github.com/eoger/tabcenter-redux/wiki/Custom-CSS-tweaks

**Comment by ugggf** [comment]
Ok, this worked - thanks. I'm having the empty bar issue (described by RalfJung) both in normal and private windows but that's not much of a problem.

**Comment by lopis** [comment]
@ugggf Ctrl+Alt+Shift+I is your best friend to find which chrome elements and which styles to change ;)

**Comment by hkmix** [comment]
On macOS, if you want to merge the title bar without window buttons overlaying the navigation, you can still do it, just with the following

    #nav-bar-customization-target {
      margin-left: 75px !important;
    }

which will push the nav bar just far enough to accommodate the three buttons.

![macOS merged title bar](https://user-images.githubusercontent.com/8205094/32645090-6ed7085e-c5b3-11e7-9bc5-3f0e5ad3b33f.png)

**Comment by avamk** [comment]
I tried the following customisations via Tab Center Redux's custom CSS panel:

```
@-moz-document url("chrome://browser/content/browser.xul") {
  #TabsToolbar {
    visibility: collapse !important;
  }
}
```

And:

```
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");
@-moz-document url("chrome://browser/content/browser.xul") {
  #TabsToolbar {
    visibility: collapse;
  }
}
```

And:

```
#tabbrowser-tabs {
  visibility: collapse;
}
```

However, my horizontal tab bar remains unchanged in Firefox 57. Am I missing something?

**Comment by jplatte** [comment]
@avamk The custom CSS panel is not where you put the CSS. You want [userChrome.css](http://kb.mozillazine.org/index.php?title=UserChrome.css&printable=yes).

**Comment by avamk** [comment]
> The custom CSS panel is not where you put the CSS. You want userChrome.css.

Thank you @jplatte! It worked, sorry about the confusion. I thought you could alter stuff through the Tab Center Redux Custom Stylesheet box, I wonder what it's for, then?

**Comment by jplatte** [comment]
@avamk If that was possible then the extension could just always have the CSS for hiding the default tab strip included. The custom stylesheet thing is for restyling the sidebar if you don't like the default look.

**Comment by mmastrac** [comment]
I've got a slightly improved `userChrome.css` that hides the top tabs and the black bar (merging the window controls in) and hides the sidebar header _only_ if the tabs are showing there.

This is OSX only!

```
@namespace xul url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);
#TabsToolbar { visibility: collapse !important; }
#nav-bar { border-left: 70px solid var(--toolbar-bgcolor); }
#sidebar-box[sidebarcommand="_0ad88674-2b41-4cfb-99e3-e206c74a0076_-sidebar-action"] sidebarheader { visibility: collapse !important; }
```

**Comment by panosl** [comment]
@mmastrac Thank you, this looks sweet af.

**Comment by xlf1024** [comment]
Win10 version of @mmastrac 's stylesheet, add this as `/chrome/userChrome.css`
(tested with the included dark theme in compact mode)
note that the alignment is not perfect yet...
```css
@namespace xul url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);
@-moz-document url("chrome://browser/content/browser.xul") {
  #TabsToolbar { visibility: collapse !important; }
  #main-window:not([drawtitle="true"]):not([inFullscreen="true"]) #nav-bar { border-right: 140px solid var(--toolbar-bgcolor); }
  #titlebar{
    margin-bottom: -29px !important;
  }
  #titlebar-buttonbox{
    height: 29px !important;
    border-bottom: 0px !important;
    vertical-align: middle;
    z-index: 2 !important;
  }
}
```

**Comment by gaby2300** [comment]
Hello,

I discovered that whenever I toggle off or disable this app, all my tabs
disappear.

I'd like to know if this is the expected behavior or if it is a bug. (I
have hidden the tabs bar with the suggested chrome CSS file)


Best regards,
Gabriela
QA Mozilla Hispano Team Responsible


http://www.mozilla-hispano.org

**Comment by xlf1024** [comment]
@gaby2300 Yes, the User Style Sheets don't check in any way, whether or not the Addon is actually active, they just hide the horizontal tabs, so this *is * expected, though not optimal at all. Still, they are just a workaround until the respective APIs get exposed for eoger to support hiding directly from the addon.

**Comment by gaby2300** [comment]
@eoger xlf1024 Many thanks for such a quick reply! What if I don't mind recovering the horizontal tabs? Should I erase the chrome CSS file?

**Comment by xlf1024** [comment]
@gaby2300 Yes, just erase it or delete the rules you copied from here (if there are more than those in it).
(and restart FF)

**Comment by gaby2300** [comment]
@xlf1024 Will do, thanks!
Just a question: whenever the respective APIs get exposed for eoger to support hiding directly from the addon, will this issue be updated accordingly or is there another issue I should follow?

**Comment by dos1** [comment]
@gaby2300 Yeah, seems like it would be this issue :)

**Comment by gaby2300** [comment]
@dos1 Great, thanks!

**Comment by ariasuni** [comment]
@RalfJung @eoger I personally use:

```
#TabsToolbar {
  visibility: collapse;
}
```

But then, it’s much less obvious when you’re in private browsing mode.

**Comment by jronallo** [comment]
In order to deal with https://github.com/eoger/tabcenter-redux/issues/276 while still mostly hiding the default top tab strip, I've just started using the following which shrinks the top tab bar and then on hover shows it giving me access to the context menu. Not perfect, but seems like a start at a temporary fix for me.

```css
:root {
  --tab-min-height: 5px !important;
}

#TabsToolbar {
  /* visibility: collapse !important; */
  height:5px !important;
  min-height: 5px !important;
}

#TabsToolbar:hover {
  height:40px !important;
  transition-delay: 1s;
}
```

**Comment by lopis** [comment]
@jronallo actually, I implemented it such that when I press ALT key to reveal the menu bar, it displays the tab strip using the CSS sibling selector. Otherwise, it stays hidden. Of course this only works in systems that hide the menu bar.

**Comment by jronallo** [comment]
@lopis Which solution are you using? I'd like to try to see if it works on Linux.

**Comment by lopis** [comment]
Sure, here's how I do it:

    /* Hides the tab strip when the menu bar is hidden */
    #toolbar-menubar[inactive="true"] + #TabsToolbar {
      visibility: collapse !important;
    }

**Comment by Rictusempra** [comment]
@eoger The API you required has landed on 60 (with user specification). Is there any plan on this?

**Comment by danielmotaleite** [comment]
More info how to apply this change... and another tweaks:

https://github.com/eoger/tabcenter-redux/wiki/Custom-CSS-tweaks

**Comment by gbaderg** [comment]
Sweet, thanks guys!!
Here's my CSS working well on Ubuntu 18.04.01 Mate on Black theme. 
_Note that I like to keep the Sidebar header to switch between Bookmarks, History and open Tabs._

/* Applies a black theme to all Sidebar options */
#sidebar-box {
  background: #333 !important;
  color: #EEE !important;
}

/* Reduces the height of the Sidebar Header and applies a dark theme */
#sidebar-box #sidebar-header {
  background: #444 !important;
  color: #EEE !important;
  font-size: 12px !important;
  margin-top: -8px !important;
  margin-bottom: -8px !important;
}

/* Hides the tab strip when the menu bar is hidden */
#toolbar-menubar[inactive="true"] + #TabsToolbar {
  visibility: collapse !important;
}

**Comment by FrobtheBuilder** [comment]
> 
> 
> Win10 version of @mmastrac 's stylesheet, add this as `/chrome/userChrome.css`
> (tested with the included dark theme in compact mode)
> note that the alignment is not perfect yet...
> 
> ```css
> @namespace xul url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);
> @-moz-document url("chrome://browser/content/browser.xul") {
>   #TabsToolbar { visibility: collapse !important; }
>   #main-window:not([drawtitle="true"]):not([inFullscreen="true"]) #nav-bar { border-right: 140px solid var(--toolbar-bgcolor); }
>   #titlebar{
>     margin-bottom: -29px !important;
>   }
>   #titlebar-buttonbox{
>     height: 29px !important;
>     border-bottom: 0px !important;
>     vertical-align: middle;
>     z-index: 2 !important;
>   }
>   
>   #sidebar-box[sidebarcommand="_0ad88674-2b41-4cfb-99e3-e206c74a0076_-sidebar-action"] sidebarheader { visibility: collapse !important; }
> }
> ```

This was perfect for me, but it no longer works with the latest update. Window buttons just don't display. I fixed it as follows:
```css
@namespace xul url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);
@-moz-document url("chrome://browser/content/browser.xul") {
  
  #main-window:not([drawtitle="true"]):not([inFullscreen="true"]) #nav-bar { border-right: 140px solid var(--toolbar-bgcolor); }
  #titlebar {
    margin-bottom: -31px !important;
  }
  #tabbrowser-tabs[orient="horizontal"] {
    visibility: collapse !important;
  }
  
  
  #sidebar-box[sidebarcommand="_0ad88674-2b41-4cfb-99e3-e206c74a0076_-sidebar-action"] sidebarheader { visibility: collapse !important; }
}
```
![image](https://user-images.githubusercontent.com/2354433/49919023-fc1b6b80-fe59-11e8-8648-b0af75aacddc.png)
Very slick. At least until they break it again.

**Comment by mmastrac** [comment]
This broke on OSX as well with Firefox 64 or 65 beta.

I adapted @FrobtheBuilder's modifications, but I can't figure out how to get rid of the tiny titlebar...

```
@namespace xul url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);
@-moz-document url("chrome://browser/content/browser.xul") {
  #tabbrowser-tabs[orient="horizontal"] { visibility: collapse !important; }
  #main-window:not([drawtitle="true"]):not([inFullscreen="true"]) #nav-bar { solid var(--toolbar-bgcolor); }
  #sidebar-box[sidebarcommand="_0ad88674-2b41-4cfb-99e3-e206c74a0076_-sidebar-action"] sidebarheader { visibility: collapse !important; }
}
```

<img width="274" alt="image" src="https://user-images.githubusercontent.com/512240/49960457-71745400-fecd-11e8-9e23-f6517f6ab48d.png">

**Comment by mmastrac** [comment]
Alright, managed to get it passable on OSX:

```
@namespace xul url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);
@-moz-document url("chrome://browser/content/browser.xul") {
  #TabsToolbar * { background-color: var(--toolbar-bgcolor) }
  #tabbrowser-tabs[orient="horizontal"] { visibility: collapse !important; }
  #main-window:not([drawtitle="true"]):not([inFullscreen="true"]) #nav-bar {
        position: absolute !important; top: 0; left: 0; right: 0; margin-left: 74px; margin-right: 32px
  }
  #main-window:not([drawtitle="true"]):not([inFullscreen="true"]) #navigator-toolbox { background-color: var(--toolbar-bgcolor) }
  #main-window:not([drawtitle="true"]):not([inFullscreen="true"]) #PersonalToolbar { margin-top: 14px }
  #PanelUI-button { position: absolute; right: -32px; top: 0 }
  #sidebar-box[sidebarcommand="_0ad88674-2b41-4cfb-99e3-e206c74a0076_-sidebar-action"] sidebarheader { visibility: collapse !important; }
}
```

It's going to be bit more fragile than the previous styles. Anyone feel like cleaning this up a bit? :)

**Comment by FrobtheBuilder** [comment]
The solution from @mmastrac no longer seems to work on macOS. It's really broken looking in the latest nightly, which means it will be broken in normal firefox soon at the very least.

**Comment by mmastrac** [comment]
@FrobtheBuilder Still sort of working for me on 67beta on macOS. It has an annoying black box that I wasn't able to get rid of and the buttons aren't where I'd like them to be though.

**Comment by gtback** [comment]
I think there is some weirdness in Nightly in general (caveat: I haven't investigated other than noticing that the "Dark" theme doesn't work in the default tab strip anymore, but does in the Tab Center panel)

**Comment by jplatte** [comment]
Anyone else having issues with the tab strip reappearing in Firefox Nightly 69? I have the new `toolkit.legacyUserProfileCustomizations.stylesheets` in `about:config` set to `true`, so that doesn't seem to be the problem.

**Comment by ariasuni** [comment]
@jplatte I’m on Linux and it’s working fine with latest Nightly. What CSS code do you use to (try to) hide the tabstrip?

**Comment by jplatte** [comment]
Same as you, apparently (https://github.com/eoger/tabcenter-redux/issues/15#issuecomment-361568245). I've also tried to add the xul namespace thing + hiding `#tabbrowser-tabs[orient="horizontal"] `, but that didn't change anything.


I'm on Linux too, with some experimental features enabled on top of using Nightly (WebRender + direct Wayland support), but I don't see how that would affect custom stylesheets.

**Comment by jplatte** [comment]
This broke on another setup of mine after updating from 69.0a1 (2019-05-21) to 69.0a1 (2019-05-27) (Build ID `20190527215312`).

**Comment by FrobtheBuilder** [comment]
Public service announcement: If you're using nightly and already made the about:config change but your userchrome customization still isn't working, you need to change the `@-moz-document` selector from `browser.xul` to `browser.xhtml`. I was struggling with this issue for a while but I finally found the solution.
macOS example:
```css
@namespace xul url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);
@-moz-document url("chrome://browser/content/browser.xhtml") {
  #tabbrowser-tabs[orient="horizontal"] { visibility: collapse !important; }
  #main-window:not([drawtitle="true"]):not([inFullscreen="true"]) #nav-bar { solid var(--toolbar-bgcolor); }
  #sidebar-box[sidebarcommand="_0ad88674-2b41-4cfb-99e3-e206c74a0076_-sidebar-action"] sidebarheader { visibility: collapse !important; }
}
```
This should work for all other OS variants as well.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1534407.

@jplatte this might solve your problem.

**Comment by ariasuni** [comment]
I don’t use @-moz-document and it works. What’s the point of using at all?

**Comment by FrobtheBuilder** [comment]
By the way, I fixed up @mmastrac's macOS solution to work properly with the latest nightly.
```css
@namespace xul url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);
@-moz-document url("chrome://browser/content/browser.xhtml") {
  #TabsToolbar * {
    background-color: var(--toolbar-bgcolor)
  }
  #TabsToolbar {
    height: 40px;
  }
  #tabbrowser-tabs[orient="horizontal"] { visibility: collapse !important; }
  #main-window:not([drawtitle="true"]):not([inFullscreen="true"]) #nav-bar {
        position: absolute !important; top: 0; left: 0; right: 0; margin-left: 74px; margin-right: 32px
  }
  #main-window:not([drawtitle="true"]):not([inFullscreen="true"]) #navigator-toolbox { background-color: var(--toolbar-bgcolor) }
  #main-window:not([drawtitle="true"]):not([inFullscreen="true"]) #PersonalToolbar { margin-top: 14px }
  #PanelUI-button { position: absolute; right: -32px; top: 0 }
  #sidebar-box[sidebarcommand="_0ad88674-2b41-4cfb-99e3-e206c74a0076_-sidebar-action"] sidebarheader { visibility: collapse !important; }
  hbox#nav-bar-customization-target {
    width: 100%;
    padding-right: 10px;
  }
  toolbaritem#PanelUI-button {
    margin-top: 5px !important;
  }
}
```

Note: this only works if you don't have an overflow menu. If you do, you can probably set that `width: 100%` to something slightly less using `calc` to make room for it. I'm trying to figure out a better solution.

**Comment by FrobtheBuilder** [comment]
@ariasuni https://developer.mozilla.org/en-US/docs/Web/CSS/@document

I assume it restricts the styles to only the browser chrome document, just in case the selectors might conflict with page content, I guess.

**Comment by ariasuni** [comment]
Right, I thought it was some XUL/XML thingy and not CSS.

`@namespace xul` is probably not necessary though (and even more probably if the document is an `xhtml`), right?

**Comment by martinthomson** [comment]
This is working for me on Win10 as the simplest possible fix:

```css
#toolbar-menubar[inactive="true"] + #TabsToolbar {
  visibility: collapse !important;
  margin-bottom: 0;
}
#titlebar {
  margin-bottom: calc(-1 * var(--tab-min-height)) !important;
}
#toolbar-menubar + #TabsToolbar {
  margin-bottom: var(--tab-min-height) !important;
}

#sidebar-box[sidebarcommand="_0ad88674-2b41-4cfb-99e3-e206c74a0076_-sidebar-action"] sidebarheader { visibility: collapse !important; }
```

It doesn't look great when I choose "touch" density in the customize menu, but it is otherwise OK.  I suspect that some of the other hacks won't work with the recent changes in Nightly, which is what motivated me to try fixing this.

**Comment by ariasuni** [comment]
As stated in the [Tab Center Reborn wiki](https://framagit.org/ariasuni/tabcenter-reborn/wikis/home#userchromecss-tweaks), this works in all current versions:

```css
#TabsToolbar:not([customizing="true"]) {
  visibility: collapse !important;
}
/* if the titlebar is also hidden and your browser is maximized,
 * clicking on the top pixel of the screen should trigger menu items (Fitt’s law) */
#toolbar-menubar {
  padding-top: 0px !important;
}
```
