### ISSUE TITLE
Show a drop shadow between pinned and non-pinned tabs

### ISSUE THREAD

**Issue by kewisch** [eoger/tabcenter-redux#240]
I've sometimes thought "where did all my tabs go" just because it looked like a continuous list. Firefox has a nice subtle drop shadow between pinned and non-pinned tabs, which disappears if you are at the start of the tab list. Maybe this could be added here as well?

<img width="71" alt="image" src="https://user-images.githubusercontent.com/607198/32406287-16c38ff2-c176-11e7-9cac-a543088e453e.png">

**Comment by kewisch** [comment]
I guess something like:

```css
#tablist { 
  box-shadow: inset 0px 10px 10px -10px rgba(0, 0, 0, 0.3); 
}
``` 
would do it, but this does not make it go away when scrolled to the top. I don't know if there is a fun pseudo-class for that kind of thing. Also maybe someone who is visually pedantic can fix the box shadow, there is a white area on the right side for me.

**Comment by dos1** [comment]
I'm using this:
```css
#pinnedtablist {
  box-shadow: 0px 1px 0px hsla(0, 0%, 0%, 0.2);
  z-index: 1;
}
#pinnedtablist .tab:last-of-type {
  border-bottom: none;
}
```
