### ISSUE TITLE
Make pinned tabs always visible

### ISSUE THREAD

**Issue by Keith94** [eoger/tabcenter-redux#27]
Requesting to have pinned tabs always displayed at the top of the sidebar. Currently having them disappear when scrolled down defeats the purpose in a way.

**Comment by Smile4ever** [comment]
This wasn't done in TabCenter, can we make this optional?

**Comment by Livven** [comment]
@eoger Is this approach worth exploring:

```css
.tab.pinned .tab-title-wrapper,
.tab.pinned .tab-pin {
    display: none;
}

.tab.pinned {
    position: fixed;
    background: hsl(0, 0%, 99%);
    z-index: 1;
}

/* auto-generate these in JS as required */

.tab.pinned:nth-child(2) {
    margin-left: 38px;
}

.tab.pinned:nth-child(3) {
    margin-left: 76px;
}

.tab.pinned:nth-child(4) {
    margin-left: 114px;
}

.tab.pinned:nth-child(5) {
    margin-left: 152px;
}

.tab.pinned:nth-child(6) {
    margin-left: 190px;
}

.tab.pinned:nth-child(7) {
    margin-left: 228px;
}

.tab.pinned:nth-child(8) {
    margin-left: 266px;
}

.tab.pinned:nth-child(9) {
    margin-left: 304px;
}
```

This approach would not substantially change the current HTML markup. The other obvious approach I could think of would be splitting pinned tabs into a separate `<div>`-container, which to me seems a bit more complicated and more problematic in the long run.

As I [mentioned](https://github.com/eoger/tabcenter-redux/pull/58#issue-236752001) though my CSS is very rusty so there might a way easier and more elegant way to accomplish this.
