### ISSUE TITLE
No class for 'no-read-yet' tab

### ISSUE THREAD

**Issue by bostiq** [eoger/tabcenter-redux#283]
Hi, at the moment is not possible to style loaded tabs that haven't been read yet.
All it needs is a an unread class in the html of the unread tab.
Do you think you can implement it?

I believe it's a nice feature especially in ajax sites where the content can update.
that way you can style the tab (eg: red border ) and attract attention on the new content.

Thanks! and keep up with the good work!

**Comment by dos1** [comment]
Something like
```css
[notselectedsinceload="true"] {
  font-weight: bold;
}
```
? :)
