### ISSUE TITLE
Custom CSS to move tab close button to left and hide favicon on hover (like Vivaldi OSX)

### ISSUE THREAD

**Issue by tze** [eoger/tabcenter-redux#291]
As OSX user I'm used to having the close button on the left side of a tab. This works fine via
```
.tab-close {
    right: unset;
    left: 5px;
}
```
However this only moves the tab close button to the left while still displaying the favicon. This looks allright but it would be nice to hide the favicon on hover. I can't manage to do that.

**Comment by dos1** [comment]
It's very easy:
```css
.tab:hover:not(.pinned) .tab-icon-wrapper {
  opacity: 0;
}
```

With such setup, you might also want to adjust the gradient on the right:
```css
.tab:hover > .tab-title-wrapper::after {
  transform: translateX(36px);
}
```
