### ISSUE TITLE
Is there a way to disable throbber animation?

### ISSUE THREAD

**Issue by sprnza** [eoger/tabcenter-redux#320]
Hi there!
Thanks for the extension, it made me switched back to FF.
Just a little question: is there a way to disable tab-throbber animation?
userChrome.css doesn't affect tabcenter-redux.

```
.tab-throbber { visibility: hidden !important; }
```

**Comment by eoger** [comment]
Check out the extension settings page, you can input custom CSS there.

Here's a solution:
```css
.tab-icon::before {
  display: none;
}
```
This one will hide the throbbed, but you'll see a blank favicon while loading.
And then you can add this:
```css
.tab.loading .tab-icon {
  background-image: url("img/defaultFavicon.svg") !important;
}
```
Which will show a static default favicon (well, you could provide your own!) during loading.
