### ISSUE TITLE
styling of unread tabs doesnt work

### ISSUE THREAD

**Issue by Siarhei-Yarkavy** [eoger/tabcenter-redux#377]
I have 2 things for that issue.

1) Example https://github.com/eoger/tabcenter-redux/wiki/Custom-CSS-tweaks#change-styling-of-unread-tabs-283 doesn't work on my windows 10 64bit, FF62 64 bit dev, dark theme set

2) How I can make "unread/not loaded" tabs same font as loaded (not so thin/grayed font )

**Comment by Keith94** [comment]
1. It works for me, so I have no idea.

2. Try this CSS.
```css
.tab.discarded .tab-title,
.tab.discarded .tab-meta-image {
  opacity: 1.0 !important;
}
```
