### ISSUE TITLE
Inverse (from default) order causes inconsistency in where new tabs open

### ISSUE THREAD

**Issue by OJFord** [eoger/tabcenter-redux#381]
With:
```css
#tablist {
  flex-direction: column-reverse;
  display: flex;
  flex: 0 0 auto;
}
.tab.pinned {
  order: 1;
}
```
as suggested in the Wiki to reverse the order, <kbd>Ctrl</kbd>-<kbd>T</kbd> opens tabs at the top, but clicking links (whether within Firefox or from another application) opens tabs at the bottom.
