### ISSUE TITLE
how do i zoom tab thumbnails?

### ISSUE THREAD

**Issue by iconotic** [eoger/tabcenter-redux#424]
First , thanks for the masterpiece addon it made my firefox shine 
im using tab center redux with thumbnail only and im trying to zoom tab thumbnails within the thumbnail container, for both a clear view and easy identification of the website, can you tell me what css code to use to achieve this? [here is an illustration of what i want](https://i.imgur.com/z9sAJNG.jpg)

**Comment by ariasuni** [comment]
You can use:

```css
#tablist-wrapper:not(.shrinked) #tablist .tab-meta-image,
#tablist-wrapper:not(.shrinked) #pinnedtablist:not(.compact) .tab-meta-image {
  background-size: 700% !important;
}
```
