### ISSUE TITLE
Remove Icons Altogether

### ISSUE THREAD

**Issue by jimmy502** [eoger/tabcenter-redux#426]
Is it possible to remove icons altogether on the side tabs and display only the tab title text?

**Comment by ariasuni** [comment]
You can use this custom CSS:

```css
.tab-meta-image {
  display: none;
}
```
